version: "3.8"

services:
  funcionarios-api:
    build: funcionarios
    networks:
      - app-tier
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - app-tier

networks:
  app-tier: 
    name: app-tier
    driver: bridge
